### ISSUE TITLE
Error while building with webpack 2.2.0

### ISSUE THREAD

**Issue by NothingWeAre** [MattyRad/vue-i18n#5]
Error while building with webpack 2.2.0.
`Uncaught TypeError: Cannot assign to read only property 'exports' of object '#<Object>'`
Most likely related to this:
https://github.com/webpack/webpack/issues/4039

**Comment by MattyRad** [comment]
https://github.com/MattyRad/vue-i18n/commit/ed66c29fbe8f86f9bfbad6e6c52f15fad5659624 This should handle that single error, let me know if there are any other problems with webpack.
